apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: go-demo
  name: go-demo
  namespace: go-demo
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: go-demo
status:
  loadBalancer: {}
